name: Build

on:
  pull_request:

concurrency:
  group: build-pr-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4096M -Dorg.gradle.daemon=false -Dorg.gradle.parallel=true -Dorg.gradle.caching=true"

jobs:
  android:
    name: Build Android
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Gradle setup
        uses: ./.github/actions/gradle-setup

      - name: Build Android debug APK
        run: ./gradlew :android:assembleDebug

      - name: Upload Android debug APK
        uses: actions/upload-artifact@v7
        with:
          name: android-apk
          path: android/build/outputs/apk/debug/*.apk

#  ios:
#    name: Build iOS simulator app
#    runs-on: macos-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v7
#
#      - name: Gradle setup
#        uses: ./.github/actions/gradle-setup
#
#      - name: Set Xcode version
#        run: sudo xcode-select -s /Applications/Xcode_26.2.app/Contents/Developer
#
#      - name: Build iOS simulator app
#        run: |
#          xcodebuild build \
#          -project iosApp/SaltMine.xcodeproj \
#          -configuration Debug \
#          -scheme JetcasterMigration \
#          -sdk iphonesimulator \
#          -arch arm64 \
#          -derivedDataPath ./build \
#          -verbose

      - name: Upload App Folder
        uses: actions/upload-artifact@v7
        with:
          name: iphonesimulator-app
          path: build/Build/Products/Debug-iphonesimulator/*

  desktop-macos:
    name: Build Desktop macOS
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Gradle setup
        uses: ./.github/actions/gradle-setup

      - name: Build macOS DMG
        run: ./gradlew :desktop:packageDmg

      - name: Upload macOS DMG
        uses: actions/upload-artifact@v7
        with:
          name: desktop-macos-dmg
          path: sharedUi/build/compose/binaries/main/dmg/*.dmg

  desktop-windows:
    name: Build Desktop Windows
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Gradle setup
        uses: ./.github/actions/gradle-setup

      - name: Build Windows MSI
        run: ./gradlew :desktop:packageMsi

      - name: Upload Windows MSI
        uses: actions/upload-artifact@v7
        with:
          name: desktop-windows-msi
          path: desktop/build/compose/binaries/main/msi/*.msi

  desktop-linux:
    name: Build Desktop Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Gradle setup
        uses: ./.github/actions/gradle-setup

      - name: Build Linux DEB
        run: ./gradlew :desktop:packageDeb

      - name: Upload Linux DEB
        uses: actions/upload-artifact@v7
        with:
          name: desktop-linux-deb
          path: desktop/build/compose/binaries/main/deb/*.deb

#  wasm:
#    name: Build Wasm
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v7
#
#      - name: Gradle setup
#        uses: ./.github/actions/gradle-setup
#
#      - name: Build Wasm distribution
#        run: ./gradlew :webApp:wasmJsBrowserDistribution
#
#      - name: Upload Wasm app
#        uses: actions/upload-artifact@v7
#        with:
#          name: wasm-app
#          path: webApp/build/dist/wasmJs/productionExecutable/
